import makeWASocket from './Socket';
import makeWALegacySocket from './LegacySocket';
export * from '../WAProto';
export * from './Utils';
export * from './Types';
export * from './Defaults';
export * from './WABinary';
export declare type WALegacySocket = ReturnType<typeof makeWALegacySocket>;
export { makeWALegacySocket };
export declare type WASocket = ReturnType<typeof makeWASocket>;
export declare type AnyWASocket = WASocket | WALegacySocket;
export default makeWASocket;
